---
- hosts: RedHatServers
  gather_facts: true
  tasks:
    # ----------------------------online---------------------------------------------#
    # - name: Install the Zabbix agent
    #   yum:
    #     name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-agent-5.0.0-1.el7.x86_64.rpm
    # - name: Configure the Zabbix agent
    #   replace:
    #     path: /etc/zabbix/zabbix_agentd.conf
    #     regexp: "{{item.regexp}}"
    #     replace: "{{item.replace}}"
    #   with_items:
    #     - { regexp: "^Server=127.0.0.1$", replace: "Server={{zabbix_server}}" }
    #     - {
    #         regexp: "^ServerActive=127.0.0.1$",
    #         replace: "ServerActive={{zabbix_server}}",
    #       }
    #     - {
    #         regexp: "^Hostname=Zabbix server$",
    #         replace: "Hostname={{ansible_hostname}}",
    #       }
    #   vars:
    #     - zabbix_server: zabbix-server.brazilsouth.cloudapp.azure.com
    # - name: Start the Zabbix agent service
    #   service:
    #     name: zabbix-agent
    #     state: started
    #     enabled: yes
    # ------------------------------------------------------------------------------#
    - name: copy rpm file to hosts
      copy:
        src: /home/armin/ansible/zabbix-project/pkg/zabbix-agent-5.0.0-1.el{{ansible_distribution_major_version}}.x86_64.rpm
        dest: "{{destpkg}}"
      when:
        - ansible_distribution == "CentOS"
    # ------------------------------------------------------------------------------#
    - name: install zabbix agent rpm file from package
      yum:
        name: "{{destpkg}}"
        state: present
      when:
        - ansible_distribution == "CentOS"
    # ------------------------------------------------------------------------------#
    - name: Transfer config file to hosts
      ansible.builtin.template:
        src: /home/armin/ansible/zabbix-project/conf/zabbix_agentd-el{{ansible_distribution_major_version}}.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: 0744
    # ------------------------------------------------------------------------------#
    - name: restart and enable service zabbix agent
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes
      when:
        - ansible_distribution_major_version == "7"
